# basedir = workflow.basedir
# print("Base dir: {}".format(basedir))

configfile: "config/config.yaml"

##### load rules #####

include: "rules/copy_embl_file.smk"
include: "rules/make_json_header_footer.smk"
include: "rules/split_embl_file.smk"
include: "rules/run_pangolin.smk"
include: "rules/convert_to_json.smk"
# include: "rules/join_json.smk"
include: "rules/join_json_entries.smk"
include: "rules/complete_json.smk"

##### target rules #####

rule all:
    input: "covid19-lineages.json"
